[build]
  publish = "public"
  command = "gatsby build"
  functions = "functions-build"
[build.environment]
  NODE_VERSION = "12.12.0"
  NPM_VERSION = "6.13.0"
[[headers]]
  for = "/*"
[headers.values]
  Cache-Control = "public, max-age=31536000"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Access-Control-Allow-Origin = "*"
  Vary = "Accept-Encoding"
  Feature-Policy = "geolocation 'self' https://publiuslogic.com; autoplay 'none'; sync-xhr 'self' https://publiuslogic.com"
[[headers]]
for = "/assets/*"
[headers.values]
    Cache-Control = "public, max-age=31536000"