ratings:
  allowedFields: ["rating", "postPath", "message"]
  branch: "master"
  commitMessage: "Rating PubliusLogic"
  filename: "rating{@timestamp}"
  format: "json"
  generatedFields:
    date:
      type: date
      options:
        format: "timestamp-seconds"
  moderation: false
  name: "publiuslogic"
  path: "_data/ratings/"
  requiredFields: ["rating", "postPath"]
  recaptcha:
    enabled: false
mailgun:
  domain: publiuslogic.com
  api_key: key-2b558e817d64430627835b191d736d92
  # Example automation using Mailgun notifications
automation:
  trigger:
    platform: event
    event_type: SPECIAL_EVENT
  action:
    service: notify.mailgun
    data:
      title: "Something special has happened"
      message: "This a test message from Home Assistant"
      data:
        images:
          - ./bafcd30dffce3a8d81bb7ec738ec2688.png
          - ./bafcd30dffce3a8d81bb7ec738ec2688.png